# Koneksi Database Supabase
spring.datasource.url=jdbc:postgresql://db.jquildkylqapabwkbyee.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=jefri123##@@
spring.datasource.driver-class-name=org.postgresql.Driver

# Konfigurasi JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Pemetaan Otomatis Tipe Data JSONB Supabase untuk Hibernate 6/7
# (Sudah diperbaiki: Teks komentar wajib diawali tanda pagar)
spring.jpa.properties.hibernate.type.json_format_mapper=jackson